### ISSUE TITLE
Congrats on the great robotnix workflow 👍🏻 little query on the initial build

### ISSUE THREAD

**Issue by mannp** [NiklasGollenstede/lineage-build#1]
Hi @NiklasGollenstede congrats on the great robotnix workflow 👍🏻 

Not sure if this is okay for others to use, but I am unclear how to intiate the initial build, to populate the build directory.

I tried 'nix flake show' to give me some idea of what is available and it fails on patching against robotnix.

I have successful builds on my own flake, but they are now very out of date, so I saw you update your device trees and app apks prior to building, which is what I am intersted in :)

Thank in advance if you have time.

**Comment by NiklasGollenstede** [comment]
Hi!
Yes, feel free to use this. Though my publishing here was mostly a "I hope this is done now, 'cuz I've spent too much time on this already" move.

My builds had also been failing for the past few weeks, and I couldn't be bothered to check why -- seems like Nix wanted to update some inputs (why?!) but failed due to file permissions. I fixed that for me now, but don't know whether the builds work now (rebuilding the old version looks good; I am yet to try updating).

Anyway. The `module.nix.md` describes how the build is done, though partially only in code. I don't think there would be anything special about the first build. It builds from scratch every time (except that it would reuse Nix components, if present).

My system configuration contains this:
```nix
    services.lineage-build.enable = true;

    my.network.nginx.tlsTerminate."lineage.niklasg.de" = {
        directory = "/app/lineage-build/certs/lineage.niklasg.de";
    };

    wip.fs.temproot.remote.mounts = {
        "/app/lineage-build/config" = { mode = "770"; uid = config.ids.uids.lineage-build; gid = config.ids.gids.lineage-build; };
        "/app/lineage-build/keys" = { mode = "750"; uid = config.ids.uids.lineage-keys; gid = config.ids.gids.lineage-build; };
        "/app/lineage-build/certs" = { mode = "750"; };
    };
    wip.fs.temproot.local.mounts = {
        "/app/lineage-build/build" = { mode = "775"; uid = config.ids.uids.lineage-build; gid = config.ids.gids.lineage-build; };
    };
    nix.gc.automatic = false; # got to set good gc roots first ...
```
So it really only enables the module (and creates the directories as described in the module file).

If you set up the directories as described (I suppose you could ignore the user stuff for starters) and call `nix run ensure-keys -- $baseDir`, it should generate the signing keys.
Once that worked, try either `build-local` or `build-remote`, followed by `sign-build`.

And then enable the build service ^^

**Comment by mannp** [comment]
> Yes, feel free to use this. Though my publishing here was mostly a "I hope this is done now, 'cuz I've spent too much time on this already" move.

Lol, now that is why I am here, as I have so much time trying to get things automated and actually working with robotnix I was ready to say 'enough is enough' :) your work may help!

> Anyway. The `module.nix.md` describes how the build is done, though partially only in code. I don't think there would be anything special about the first build. It builds from scratch every time (except that it would reuse Nix components, if present).

Okay thanks, i see and have now created the keys for your device and a build seems to be populating the build dir with some staging data, so some progress for me thank you 👍🏻 

I have failed to create key a for my main device equuleus, I assume because its in the los-20 tree ... not sure yet [edit: I believe its because you have only included that devices info in the 19.1 repo, guess I need to add my device data there..]

```
│   │   ├───update-apks: package 'lineage-update-apks'
│   │   ├───update-deps: package 'lineage-update-deps'
│   │   └───update-repo: package 'lineage-update-repo'

```
I am currently doing an update-repo, which is very busy, but I am not sure what its actually doing? Is that attempting to update the los-19.1 tree to the latest?

Where is it putting all of this update-repo downloads, in /tmp as I have a small main ssd...cannot seem to see where it is putting these google downloads.

Thanks for your time here, appreciating you are likely sick of it already :)

**Comment by NiklasGollenstede** [comment]
Yes. At the time I wrote this, `robotnix` only supported los-19.1 -- not sure if that changed, and also not sure how much longer 19.1 will receive any upstream updates. You can change the los version by changing the android version in the `robotnixConfigurations` in the flake file (I did add the translation Android 13 to los-20.0 -- dunno if that is actually correct).

> Where is it putting all of this update-repo downloads[?]

I am not super sure either, but I think it clones a whole bunch of large git repos, and then keeps the HEADs in the Nix store.

**Comment by mannp** [comment]
Np, it has 17.1,18.1 and 19.1 at the moment, but most of my devices I have had to create the definitions myself, so will need to check how easy they are to incorporate into your system, if at all :)

> You can change the los version by changing the android version in the `robotnixConfigurations` in the flake file

androidVersion = 12 yes thanks 👍🏻 

> I am not super sure either, but I think it clones a whole bunch of large git repos, and then keeps the HEADs in the Nix store.

Okay thanks a lot for clarifying things :)
